### PR TITLE
Better match

### PR DESCRIPTION
**Pull request by NickeZ**
Thanks for a great tool. I made some updates.

Most importantly it now prints if a matching version is in Debian. 

I removed the "outdated" parts because I think that has nothing to do with the packages debian status.

What do you think?

### CODE REVIEW

**Comment by NickeZ** [comment]
This is before:

debstatus_before


This is after:
debstatus_after

There is quite a bit of more crates to package then I first thought.

**Comment by kpcyrd** [comment]
hey, thanks for your patch!

We're mostly tracking two things for a debian upload:
- are there any missing crates
- are there any of those problematic (outdated dependencies usually indicate extra work instead of "just works")

(there's also a known limitation, see https://github.com/kpcyrd/cargo-debstatus/issues/2)

The connection between outdated dependencies and debian packaging is that we would need to upload it with a version suffix (rust-rand vs rust-rand-0.5) and we're generally trying to avoid that and patch it to the latest version instead. Especially since this warning flags asemver incompatible update this usually requires coordination with upstream and/or patching source. I often do that ahead of time to land the patch in a new upstream release before all sub dependencies land in debian (I sent a large number of patches in the past, that's why this info is important for me).

There are some things we don't really care about in debstatus: Outdated packages that are already in debian. Those are tracked [somewhere else][1]. What we could indeed improve is the following situation:

[1]: https://qa.debian.org/developer.php?email=pkg-rust-maintainers%40alioth-lists.debian.net

Assuming `lib1` depends on `lib2 0.1.0` and we have `lib2 0.1.4` in debian. In this case our version in debian is semver compatible (debstatus sees both versions as `0.1.X`) and can be used without any problems (and debstatus is going to mark it as green).

Now assuming `lib3` depends on `lib4 0.1.9` and we have `lib4 0.1.2` in debian. In this case debstatus considers those versions equal again, but our crate isn't recent enough and debcargo is going to (rightfully) fail the build.

By looking at the screenshot it seems that's not the case with the patch though and it's looking at the root projects Cargo.lock instead of the individual crates' Cargo.toml:

- `dotenv 0.13.0` has all-green dependencies in the first screenshot
- the second screenshot lists regex 1.1.0 as invalid (because crates.io has 1.1.9)
- dotenv 0.13.0 specifies a dependency of `regex ^1.0`, which matches 1.1.0

there's a similar case for getrandom:
- `libc 0.2.55` is marked as invalid
- getrandom depends on `libc ^0.2.54`, which matches our crate

**Comment by NickeZ** [comment]
I don't have time to respond to your complete comment right now. But in the meantime I've learned about 

```
cargo +nightly generate-lockfile -Z minimal-versions
```

Applying that first and then running this PR gives the following (brighter) picture.

after_min_versions


Maybe this isn't exactly what you intended with `cargo-debstatus`, but this is  very useful for me to understand which crates needs to be added/updated.

**Comment by NickeZ** [comment]
>     * are there any missing crates

I would say that with my patch-set it is easier to find if crates are missing. Before some where indicated as installed even if the `Cargo.lock` file had a more recent version.

>     * are there any of those problematic (outdated dependencies usually indicate extra work instead of "just works")

Right, this was the part that I removed. I could remove that commit if you still like this functionality. To me it seems like an impossible task to package the latest version of all packages. Isn't it simply to run `cargo update` to get all the packages to the latest compatible versions?

The label `(outdated)` was very confusing to me until you explained it. I presumed that the crate existed in debian and was outdated. Would you be open to renaming it to something like `(X.Y.Z available on crates.io)`?

> The connection between outdated dependencies and debian packaging is that we would need to upload it with a version suffix (rust-rand vs rust-rand-0.5) and we're generally trying to avoid that and patch it to the latest version instead. Especially since this warning flags asemver incompatible update this usually requires coordination with upstream and/or patching source. I often do that ahead of time to land the patch in a new upstream release before all sub dependencies land in debian (I sent a large number of patches in the past, that's why this info is important for me).

OK, I see, so we should try to supply patches to upstream to get to the latest version? But if there already is a compatible version in sid/new, wouldn't it be better to not upgrade immediately?


> There are some things we don't really care about in debstatus: Outdated packages that are already in debian. Those are tracked [somewhere else](https://qa.debian.org/developer.php?email=pkg-rust-maintainers%40alioth-lists.debian.net). What we could indeed improve is the following situation:
> 
> Assuming `lib1` depends on `lib2 0.1.0` and we have `lib2 0.1.4` in debian. In this case our version in debian is semver compatible (debstatus sees both versions as `0.1.X`) and can be used without any problems (and debstatus is going to mark it as green).
> 
> Now assuming `lib3` depends on `lib4 0.1.9` and we have `lib4 0.1.2` in debian. In this case debstatus considers those versions equal again, but our crate isn't recent enough and debcargo is going to (rightfully) fail the build.
> 
> By looking at the screenshot it seems that's not the case with the patch though and it's looking at the root projects Cargo.lock instead of the individual crates' Cargo.toml:
> 
>     * `dotenv 0.13.0` has all-green dependencies in the first screenshot
> 
>     * the second screenshot lists regex 1.1.0 as invalid (because crates.io has 1.1.9)
> 
>     * dotenv 0.13.0 specifies a dependency of `regex ^1.0`, which matches 1.1.0

I suggest that we run "cargo minimal-versions" as mentioned above to fetch the lowest possible versions that work according to the recursive set of `Cargo.toml` files. (It isn't enough that `dotenv` needs `regex  ^1.1.0`, maybe some other dependency needs `regex ^1.1.9`.)

I also suggest that we try to help upstream to avoid depending on patch versions. Depending on something like `1.1.9` should really not be needed. All versions in the set `>=1.1.0 <1.2.0` should be feature-wise the same.


Since we don't have cargo nightly packaged in Debian, can we still recommend run cargo nightly commands during "./update.sh"?

**Pull request closed without merging**
